### ISSUE TITLE
correct dropbox image links to avoid broken images

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#137]
Users sometimes put URLs to images on dropbox. If they aren't careful, they get a URL beginning with https://www.dropbox.com/... which loads an HTML page which embeds the image. This can't be used as the value of an image src attribute.

Changing the domain to dl.dropboxusercontent.com gets a URL which returns an image instead of a web page.

I propose we recognize this in the authoring tool and automatically correcting the URL, probably any time it begins with https://www.dropbox.com. We could discuss whether we should also validate the extension, but I don't think that is probably worth the trouble.

**Comment by zijianwangjj** [comment]
for some reason, I still not able to drag and drop images from my dropbox to Dillinger.

![image](https://user-images.githubusercontent.com/35720257/43235169-6df4418a-9034-11e8-9100-9fe7d45543ba.png)

It's frustrating, any idea why?

I also tried drag and drop local file to Dillinger, no luck so far.

**Comment by zijianwangjj** [comment]
my apologies, I got the thread mixed up when searching for solutions. "Dillinger" is an online web based Markdown editing tool. Thanks for the response! : )
