### ISSUE TITLE
Mobile view fix examples in Squarespace for Storymap & Timeline

### ISSUE THREAD

**Issue by knightlab** [NUKnightLab/StoryMapJS#147]
Timeline is cut off to the right.
Storymap is made vertical.
Both Timeline and Storymap are larger than the screen for iphone 5s view.

![photo 1](https://cloud.githubusercontent.com/assets/1273899/3737993/2c389428-173c-11e4-8298-27378d99f5c5.PNG)
![photo 2](https://cloud.githubusercontent.com/assets/1273899/3737994/2c3f64f6-173c-11e4-855b-1e97d98f7e8d.PNG)
![photo 3](https://cloud.githubusercontent.com/assets/1273899/3737995/2c400ee2-173c-11e4-8c26-1cabb8773eb0.PNG)
![photo 4](https://cloud.githubusercontent.com/assets/1273899/3738000/2e448cc2-173c-11e4-8de1-0fd9b5380a0b.PNG)
![photo 5](https://cloud.githubusercontent.com/assets/1273899/3737999/2e43e0e2-173c-11e4-95df-2f71dd2b7e49.PNG)

**Comment by thejordan** [comment]
moved example site off squarespace so the above links not helpful
