### ISSUE TITLE
javascript failing to get URL prefix for uploaded files and JSON data

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#150]
Users have reported via Zendesk that URLs to Google Drive files are being rendered with *undefined* where the URL should be (image uploads in [no. 524](https://knightlab.zendesk.com/agent/#/tickets/524) and the sharing URL in [no. 532](https://knightlab.zendesk.com/agent/#/tickets/532))

Please look at this code and add better instrumentation for logging and/or notifying the user about the error condition. Ideally, we'd figure out how to reproduce this problem, but thus far I don't have a script for that, so we need to see if we can do anything to get more information when it happens. At a minimum, we should leave log messages that we can ask users to report to us. If it's possible to send a message to a system of ours which would log what happened with as much contextual information as possible, that would be really excellent. 

ZenDesk ticket 524 reports using Google Chrome, and that it happens with every image upload. Awaiting more info from ticket 532.

**Comment by jywsn** [comment]
I believe this is moot since we migrated to an S3 backend.
