### ISSUE TITLE
Twitter links need to open in new tab

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/StoryMapJS#160]
Also, need to add break word to handle long links
Example http://supermarketnews.com/map-history-mariano-s-chicago

**Comment by JoeGermuska** [comment]
I don't see that in the examples, but maybe I'm clueless. But @zachwise if that's still an issue and you can find an example, it should be a separate issue. This one is for Twitter links opening in a new tab.

Which would amount to scanning the [`tweet_text`](https://github.com/NUKnightLab/StoryMapJS/blob/master/source/js/media/types/VCO.Media.Twitter.js#L60) and adding `target="_blank"`

**Comment by jywsn** [comment]
Deployed to dev version in cdn.  See example here:

http://cdn.knightlab.com/libs/storymapjs/dev/embed/?url=https://11d5af1c404bc7d176ff751bfd82d936c751d92d.googledrive.com/host/0B8zGNfleieYRbnRxNVlyRDNENWc/published.json

**Comment by JoeGermuska** [comment]
Verified
