### ISSUE TITLE
Switching between Google accounts sends user away

### ISSUE THREAD

**Issue by lukerague** [NUKnightLab/StoryMapJS#181]
In testing for support ticket #864, I've been noticing some weird behavior that we may or may not have any control over.

In Chrome when I try to switch between accounts, it takes me to the Google page listing my Google accounts that I can sign into (https://accounts.google.com/ServiceLogin). Once I sign in, it takes me to the my account settings page. I never get redirected back to StoryMap.

In Firefox, for some reason it takes me to the NU account sign-in page (https://fed.it.northwestern.edu/umail-sso) instead of Google's, and then my inbox. Again, no redirect back to StoryMap.

**Comment by lukerague** [comment]
Actually the behavior is the same in both browsers. I only had my NU gmail account hooked into Firefox so it was defaulting straight there.

**Comment by JoeGermuska** [comment]
can you retest this now that we've made some changes to authentication and storage?

**Comment by lukerague** [comment]
Yeah, it still happens. It might not be anything we can do about, since the sign-in page is a redirect into Google's system that spits you out into your Google account settings.

**Comment by jywsn** [comment]
We can't do anything about this.  It is up to google to redirect back to our site.
