### ISSUE TITLE
Update Authoring UI to explain third party cookies

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#183]
Currently when people get to a site where they should be authorized but don't seem to be, we show them a link to email us about it.

https://github.com/NUKnightLab/StoryMapJS/blob/master/website/templates/edit.html#L721-L722

It seems increasingly the case that this only happens to Firefox users with third party cookie constraints. We should change the interface here to say so, while still probably leaving the email link. We can discuss details when you come to this.

**Comment by lukerague** [comment]
I actually submitted a pull request (#182) for this a while ago and then promptly forgot to tell you about it. The only additional thought I have since submitting it is we maybe want to also include Chrome, since it's possible to have this problem in Chrome (but it's not the default setting so it comes up less often, I've only had one Chrome ticket).

**Comment by JoeGermuska** [comment]
whoops, my bad. Perhaps we should write a single page on our support site that covers all the cases. You could start from https://knightlab.zendesk.com/entries/50376118-Message-Could-not-load-StoryMap-You-must-re-authorize-this-application- but make something which reads more authoritatively and gets to the point in the first post, without people having to sort through a conversation. Then we can link there instead of to a specific set of browser instructions.

**Comment by lukerague** [comment]
https://knightlab.zendesk.com/entries/76870909-Error-Could-not-load-StoryMap-You-must-re-authorize-this-application-

Let me know your thoughts.

**Comment by lukerague** [comment]
And I update the message in my pull (#182) to have the original message and point people to the support page above.

**Comment by JoeGermuska** [comment]
Great. I deployed that. Thank you.
