### ISSUE TITLE
Editor allows non-owners to view in edit mode

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#184]
If someone shares an "edit" link (eg http://storymap.knightlab.com/edit.html?id=0B111yCaEUL8DcnlqSTNIZ0VHYlk), the editor loads it even if the currently authenticated user is not the owner or a collaborator.

It even appears to allow changes to be saved, although they do not actually persist.

We should make sure that the current user has permission to write to the StoryMap directory/files before presenting a "populated" editor. If the user doesn't, we should revert to the "select" view with an appropriate message.

**Comment by jywsn** [comment]
Fixed 2e475171f30e7f70119632c0a7436eb94b246f94

**Comment by jywsn** [comment]
deployed to prd
