### ISSUE TITLE
Panels Cut Off 

### ISSUE THREAD

**Issue by lprunes** [NUKnightLab/StoryMapJS#187]
http://sojo.net/magazine/2014/11/story-map-great-divide
http://sojo.net/magazine/2014/12/storymap-5-game-changing-aid-groups

The maps are working fine, but the panels and paragraphs are cut off on every panel. Please help!

**Comment by lukerague** [comment]
Looks like a bug from the latest update. I submitted a pull request (#188). Once it's merged and live, the issue should stop.
