### ISSUE TITLE
open graph html

### ISSUE THREAD

**Issue by jywsn** [NUKnightLab/StoryMapJS#190]

**Comment by jywsn** [comment]
@JoeGermuska we never decided what to do about the "image" that is associated with a storymap (for open graph)

**Comment by JoeGermuska** [comment]
remind me what needed deciding

**Comment by jywsn** [comment]
You need a representative image for the thing you are sharing.  How are we going to do that GUI-wise.

**Comment by jywsn** [comment]
Apparently this is implemented and working.
