### ISSUE TITLE
unpublished error persists

### ISSUE THREAD

**Issue by lukerague** [NUKnightLab/StoryMapJS#197]
I got the same "couldn't find published" error. This time I clicked the Start Migration button again to see what happens. It takes me to my maps, where I see two maps were migrated, and the third (the one that is not published) was not migrated.

**Comment by jywsn** [comment]
Should be fixed by 60ee9b154ce557049d39eab254eb6136df4c51c8.

**Comment by lukerague** [comment]
It is
