### ISSUE TITLE
Error getting migration list: local variable 'file_list' referenced before assignment

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#205]
reported via ZenDesk. Not much more to go on. Can you see where this might come to pass?

**Comment by jywsn** [comment]
I think this will fix it:  90f4d936cbfc6dd6fc2164bfb5459dfcb22d4cb2
deployed to prd and stg

**Comment by JoeGermuska** [comment]
I notified the person who [filed this ticket](https://knightlab.zendesk.com/agent/tickets/1093) and asked for verification. Fix seems sound, so I'll close this and we can reopen if necessary.
