### ISSUE TITLE
https workaround no longer available

### ISSUE THREAD

**Issue by lukerague** [NUKnightLab/StoryMapJS#207]
As pointed out in support ticket #1109:
Prior to the migration, users who needed an ssl connection could swap "http://cdn.knightlab.com/libs/..." for "https://s3.amazonaws.com/cdn.knightlab.com/libs/..." to get a working StoryMap (or Timeline).

Post-migration, is there an https solution available?

Simply changing "http://s3.amazonaws.com/..." to "https://s3.amazonaws.com/..." does not provide a ssl connection, as I first dared to hope.

**Comment by JoeGermuska** [comment]
should be fixed in 575511c / 9ad31bd . Those changes are deployed: waiting for confirmation from ticket submitter.

**Comment by lukerague** [comment]
Submitter confirmed it's fixed.
