### ISSUE TITLE
Pre-fetch map tiles of the next view

### ISSUE THREAD

**Issue by fnorf** [NUKnightLab/StoryMapJS#209]
Clicking to the next view of a map pretty much always leads to the browser loading the map background tiles just in the moment. The user sees either flashes or more-or-less horribly ugly scaled tiles.

Please pre-fetch at least the nearest tiles for the next (or next few) view in advance so the transitions are less jarring. Best even include the path of the panning.

If you don't see the problem, try throttling your internet connection.

**Comment by JoeGermuska** [comment]
StoryMapJS uses Leaflet for map tiles. Leaflet has [chosen not to implement tile pre-fetching](https://github.com/Leaflet/Leaflet/issues/512).

Unless Leaflet changes their approach, this isn't something StoryMapJS can support.
