### ISSUE TITLE
Fix VCO.Util.urljoin and use it for languages

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#212]
StoryMap tries to load an Emoji CSS for Chrome, and also loads language files when users select other than english.  Both of these lead to similar but distinct errors:

![image](https://cloud.githubusercontent.com/assets/46313/7415888/2994c1ca-ef21-11e4-8162-c47ff3ba4316.png)

The language loading has one too many slashes, and the Emoji CSS URL doesn't correctly handle the '../' (it should be loading http://s3.amazonaws.com/cdn.knightlab.com/libs/storymapjs/latest/css/fonts/font.emoji.css)

Both of these should be fixable by making sure that [VCO.Util.urljoin](https://github.com/NUKnightLab/StoryMapJS/blob/master/source/js/core/VCO.Util.js#L280-L305) is implemented correctly. 

There should also be unit tests. Build on https://github.com/NUKnightLab/StoryMapJS/blob/master/templates/qunit.html and add that to routes served by flask.

**Comment by jywsn** [comment]
Just to clarify, this only happens in the Preview pane of the editor.

**Comment by jywsn** [comment]
Should be fixed with 73ce905b70d1c04a8e5d9eabb18bee65dae6ece3

Deployed to staging

test path is  (server)/qunit/

**Comment by jywsn** [comment]
Deployed to production
