### ISSUE TITLE
Make sure all map tiles are loaded protocol relative or HTTPS

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#223]
This [storymap](https://cdn.knightlab.com/libs/storymapjs/latest/embed/?url=https://e824365de82c1f01fce7381e87d7ad52efa85487.googledrive.com/host/0B6HiJUHbSimPWmVJaU1vcnBlN3c/published.json) gets mixed content warnings because the Storymap tiles are loaded via https:

![image](https://cloud.githubusercontent.com/assets/46313/7736470/8db5d174-ff09-11e4-9415-21f8e0e549f6.png)

**Comment by jywsn** [comment]
Fixed stamen tile and font issues

c1c725a767cfeb5ec87d8609b77e7557c3ae76b4

deployed to stg + prd
