### ISSUE TITLE
slug algorithm shouldn't pass ' characters

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#224]
A user filed a support ticket which pointed to an S3 bucket with a `'` character in it.  This seems risky for various tools that try to do smart things with URLs.

When we "slugify" bucket keys, we should stick to lowercase `a-z` and the `-` character.

**Comment by JoeGermuska** [comment]
In fact, I see now that this is the issue in the [Zendesk ticket](https://knightlab.zendesk.com/agent/tickets/1358) -- the `'` character is being entity encoded, so the AJAX call for the data file is for something which doesn't exist.

**Comment by jywsn** [comment]
Can you paste a copy of that ticket here so I can see it?

**Comment by jywsn** [comment]
Also, I can't seem to recreate this -- how you would end up with a ' in the slug.  The slugify lib is handling single quotes correctly in all my tests.

**Comment by jywsn** [comment]
Ok, so this was happening with some non-Latin character sets (Cyrillic, Arabic, etc).  Changed which slugify library we are using and re-rendered the embed pages for storymaps with problematic characters.  Should be solved going forward.
