### ISSUE TITLE
Enable multiple base maps

### ISSUE THREAD

**Issue by miloskroulik** [NUKnightLab/StoryMapJS#230]
For my use case, I would like to use Stamen Watercolor base map and add another tiled layer with label above it. Map_type setting should be an array of all defined layers.

**Comment by JoeGermuska** [comment]
I'm not sure how we would gracefully move the map from one point to another while also changing the base map. There would inevitably be flicker which I think would make for a negative user experience.

**Comment by miloskroulik** [comment]
Sorry, but this issue isn't about changing layers from point to point at all. I just would like to use multiple layers **displayed at the same time**

**Comment by JoeGermuska** [comment]
Right. I had #229 in mind and read this one too quickly. 

We won't introduce support for multiple layers in the StoryMap authoring tool in any foreseeable future: it would overcomplicated the tool for an edge use case.

In b870b4937a10d2585c284cedd38a1ef6cd7d2b46 access to the Leaflet map which StoryMap uses was exposed. It should be possible for someone with reasonable JS competence to use that to add additional map layers.

**Comment by miloskroulik** [comment]
That's understandable. Thanks for the link, I will try that approach.
