### ISSUE TITLE
Link popup should be disabled in raw HTML mode

### ISSUE THREAD

**Issue by scott2b** [NUKnightLab/StoryMapJS#233]
In the editor, the insert link popup functionality should only be available when in standard edit mode, not in raw HTML mode triggered by the Edit HTML button.

**Comment by jywsn** [comment]
I think this has something to do with the fact that the button pops up a modal.  When I add in an "image" button, it has the same problem (i.e. looks disabled but still pops up the related modal).

**Comment by jywsn** [comment]
Actually, it seems that the other non-modal-y buttons are registering clicks as well.  You just can't tell because no modal pops up.

**Comment by jywsn** [comment]
ad35ba924c246cec19ec048975ec1a8a436cc314
