### ISSUE TITLE
Rotate photos after upload

### ISSUE THREAD

**Issue by thejordan** [NUKnightLab/StoryMapJS#241]
https://knightlab.zendesk.com/agent/tickets/1441

Rotate photos - It would be great to have a feature in the Upload Media that would allow the user to rotate a photo 90 degrees.

**Comment by JoeGermuska** [comment]
There are a number of good quality free online photo editing tools. I have some hesitation about starting to add any photo editing features to StoryMapJS when these exist.

I'm not going to close this as WONTFIX just yet, but it is unlikely to be a high priority without a clearer idea that other solutions are inadequate.

See [The 9 best browser-based photo editing tools available today](http://thenextweb.com/creativity/2014/02/24/9-browser-based-photo-editing-tools/) for some alternatives.
