### ISSUE TITLE
Are there event hooks?

### ISSUE THREAD

**Issue by oragorn** [NUKnightLab/StoryMapJS#251]
Is it possible to hook to next and previous nav events?

**Comment by jywsn** [comment]
If you are creating the VCO.StoryMap object yourself in JavaScript, there is an optional fourth parameter in the constructor that allows you to pass in your own event listeners.  

The event that gets fired on slide navigation is the "change" event.  However, note that this event gets fired whenever the current slide changes, which can happen not only as a result of next/prev nav events but also as a result of clicking "Back To Beginning" or by clicking directly on a map marker to jump to a slide.

Sample usage:

```
storymap = new VCO.StoryMap('my-element-id', sm_data, sm_options, 
    // Here are where the event listeners are passed
    {
         "change": function(data) { 
            console.log("navigated to slide number "+data.current_slide);
        }
    });
```
