### ISSUE TITLE
Rewrite Google Drive URLs for Gigapixel

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#252]
If someone were to enter a URL like this for the "image directory" when creating a StoryMap

https://drive.google.com/open?id=0B1w22KMgTWuBfmg5NnpCSUc5RkVYS1FLb25jd1gxWHpWQXlscEtkWVYxbi1qbFZNVlVBVXc

We could rewrite that for them to 

http://www.googledrive.com/host/0B1w22KMgTWuBfmg5NnpCSUc5RkVYS1FLb25jd1gxWHpWQXlscEtkWVYxbi1qbFZNVlVBVXc/

in a pretty straightforward fashion.

Also, we should align the labels between the "new" UX 
**URL path for your image directory:**

and the "options" once you've passed that point
**Zoomify URL**

We should also enforce a protocol (http/https) on that value.

**Comment by jywsn** [comment]
I don't understand what/where this is:  

"Also, we should align the labels between the "new" UX 
URL path for your image directory:
and the "options" once you've passed that point
Zoomify URL"

You are referring to the modal where you create the new gigapixel storymap? You have the URL path text field and then you have width and height text fields.  What is not aligned?

**Comment by JoeGermuska** [comment]
when you make a new Gigapixel StoryMap, it asks for the first text (URL path for your image directory), and later, the same configuration value has a different label (Zoomify URL)

Since it's the same thing, it should have the same label...

**Comment by jywsn** [comment]
Ohhhh.  I thought "align" referred to the visual justification of labels.

Which label do you want to use?

**Comment by JoeGermuska** [comment]
Let's use "Base Image Directory URL"

**Comment by jywsn** [comment]
We need to do some re-design on the storymap-level options dialog -- maybe add one more tab.  There is too much stuff on the 'Display' tab for gigapixel storymaps.  The modal is too tall and runs off the bottom of the screen on my laptop.

**Comment by JoeGermuska** [comment]
This is obsolete, since Google Drive is no longer amenable for hosting Gigapixel images anyway
