### ISSUE TITLE
YouTube poster frames disappear.

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#253]
A [Zendesk user reported](https://knightlab.zendesk.com/agent/tickets/1655) that YouTube clips were not showing their poster frames.

Upon closer inspection, it seems that the first video showed it, but on advancing past that slide, the poster frame disappeared and no future YouTube videos showed theirs.

My hypothesis is that this is because we send a 'stop' message on slide advance. If this is true, we should see if we can intercept the message and only send it if we know that the video is playing. That may be easier said than done.

**Comment by jywsn** [comment]
Neither of the videos in this test are showing their poster frames.
https://s3.amazonaws.com/uploads.knilab.com/storymapjs/b275e44835f044e2365e0d682ed4671c/test-1/index.html

**Comment by JoeGermuska** [comment]
Hm. I thought I saw them before. With [this one](https://s3.amazonaws.com/uploads.knightlab.com/storymapjs/7d5cf9cfc9fa75da134291f9fe3c57fb/test-multiple-youtube-videos/index.html), I see the poster frame on the video that is on the overview. It disappears as the slide starts to transition to the next, which may be part of what led to my hypothesis. Maybe that signal happens on every slide advance, whether or not anything has ever been played?

**Comment by jywsn** [comment]
This is definitely the problem:  
https://github.com/NUKnightLab/StoryMapJS/blob/master/source/js/media/types/VCO.Media.YouTube.js#L58

When I comment out the call to pause the video, the poster frames appear just fine.

**Comment by jywsn** [comment]
f0524ae4ae4315b2ee00413efc4d8a639d802450
