### ISSUE TITLE
YouTube playback problems on iOS browsers

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#254]
A [zendesk user](https://knightlab.zendesk.com/agent/tickets/1774) reported problems with YouTube playback on [this storymap](http://interactives.dallasnews.com/test-john/finding-christina). In his report, the embed was "not playing."

In my testing, I found that I could play the video once on first loading the page, on iOS Safari and iOS Chrome. This held for my physical iPad, the iPad in the iOS Simulator, and the iPhone in the iOS Simulator.

It would be great to get more reports of cases where playback never works. If it works on first play, this is a lower priority issue, although of course still something we'd like to fix.  There's also a chance that it has to do with Google changes outside our control, since #253 is another recent change to how YouTube works in StoryMap.

I tested [a TimelineJS3 YouTube embed](http://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1XSmEXKWWlLFyt0ETEQACotj2jCLq5sO90wM5tTyg16o&font=Default&lang=en&initial_zoom=2&height=650) and found a similar problem.  

This [StoryMap](https://s3.amazonaws.com/uploads.knightlab.com/storymapjs/7d5cf9cfc9fa75da134291f9fe3c57fb/test-multiple-youtube-videos/index.html) has two videos, and also consistently demonstrates the issue. On iOS (simulated), a video can't be replayed after it finishes, but **also**, even if the first video isn't played, the second video does not play on advancing to that slide.  (The poster frame issues in #253 also manifest.)

**Comment by jywsn** [comment]
Using iOS simulator (5S), after fixing #253, the second video will play whether or not the first one is played.  However, it is still the case the any one particular video can only be played once *to completion*.  Starting, pausing, and restarting a video works fine (until it plays through to the end).

**Comment by jywsn** [comment]
Also:  while the separate player window is open, you can keep replaying the video over and over again.  But, once you close the player window and return to the StoryMap, clicking on the video (to replay the video) has no effect.

**Comment by jywsn** [comment]
Currently on hold because of deprecated API.

**Comment by jywsn** [comment]
More observations (using new iframe API):  If you play the video through to the end (state = 0 = ended), then click the 'fast forward to end' button (state = 1 = playing, then state = 2 = paused), then close the player window... if you click on it to replay the video, if works fine.

**Comment by jywsn** [comment]
@joegermuska Using the new iframe API, I was able to "fix" the problem as follows: when receiving a state change notification of 0 (playback ended), call the player method to seek to 0 (the state) and then immediately call the player method to pause (or else it will start playing again).   It's hacky, but it works.  Not sure if you want me to keep looking for a less hacky solution.

**Comment by JoeGermuska** [comment]
I think this is good enough.

**Comment by zachwise** [comment]
I think TimelineJS3 uses the same media class for youtube. Is the problem there too?

**Comment by jywsn** [comment]
Looking at the Whitney Houston example from timeline3.knightlab.com on my  iPhone 5S running iOS 8....  I can't get any of the YouTube videos in that timeline to play at all.  Probablyrelated to this:  https://github.com/NUKnightLab/TimelineJS3/issues/196  

(Similar problem has been fixed in StoryMap.)

**Comment by jywsn** [comment]
The "fix" has been added as version 0.5.3.  Will address TImelineJS3 in a big.
