### ISSUE TITLE
SnapMap import is broken

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#257]
Maybe since we switched from Google Drive? In any case, it doesn't work.

**Comment by jywsn** [comment]
It's because SnapMap is linking to select.html, which is getting redirected to /select/ without the url params.  Will fix shortly.

**Comment by jywsn** [comment]
Fixed in 2288a7ceb68a0ef5be30bd1c934639b70b913a08

**Comment by JoeGermuska** [comment]
Looks good, thanks!
