### ISSUE TITLE
Support titles with non-ascii characters

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#258]
A Zendesk user reported that a StoryMap with Ö in the title resulted in this error:

    Error publishing StoryMap: u'\xd6'

We should account for any valid characters in the title of storymaps.

**Comment by jywsn** [comment]
I was unable to recreate this on the production site.  I had no problems creating, saving, publishing a storymap using both Safari and Chrome.

**Comment by jywsn** [comment]
Also, I believe this issue should have been addressed in commit 5e2dd3342c79e02eec3b0e9d8475855445b64816 back in June,

**Comment by JoeGermuska** [comment]
closing as unreproducible
