### ISSUE TITLE
admin tool doesn't work

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#260]
I get 502 errors for most everything in the admin tool.

**Comment by jywsn** [comment]
I think this might be timeout issues.  The admin pages work fine for me locally and with staging (where there is far less data).

**Comment by scott2b** [comment]
@JoeGermuska is "admin tool" the storymap editor? Is this still an issue?

**Comment by JoeGermuska** [comment]
no, the admin tool is the thing you (@scott2b) wrote to give us insight into user data when troubleshooting!  I haven't had call to use it much lately, but now that you are closer to user support, you may have ideas for how it would help
