### ISSUE TITLE
Error loading StoryMap: The specified key does not exist.

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#262]
Thanks to a better than usual user report, I can now reliably cause this error.

To reproduce:
Create a new storymap, named, e.g. `test`
Return to "my maps" (no need to do anything to the map just made)
Create another new storymap with exactly the same name
Return to "my maps" (again, no need to enter any data)
Delete the first one (if you mouse-over the titles, you can see the target URL including the "slug"/ID for the storymap. The second one you created will have a `-1` suffix on the ID. Delete the one *without any suffix*.
Now click on the other storymap. You will see this error:
![image](https://cloud.githubusercontent.com/assets/46313/10650534/9dfe16ac-780f-11e5-86ce-4139719d94a9.png)

We should review the "deletion" code and make sure that only the indicated storymap gets deleted.

**Comment by jywsn** [comment]
60f2a25402efe50373af4f2550ace2d3adefc7de

huzzah
