### ISSUE TITLE
Support Mapbox GPX and other extra non-tilelayer assets

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#265]
A few Zendesk tickets ([2282](https://knightlab.zendesk.com/agent/tickets/2282) and [2253](https://knightlab.zendesk.com/agent/tickets/2253)) ask about using Mapbox GPX or other features beyond the base tile layer.

We should investigate the feasibility of this. It may be tricky with the integrated LeafletJS, but then, I think there are other issues with integrated LeafletJS, so this may be a nudge to reconsider that.

**Comment by karolleon** [comment]
Wow, no news on this? Would love to be able to embed GPX tracks into the maps.

**Comment by JoeGermuska** [comment]
StoryMapJS is not under active development. Adding map-level behavior is substantially complicated by the fact that the map presentation internals are based on a very old version of Leaflet (because StoryMapJS predates modern JS build systems like `npm`).  

For those who can use it, we think that Chris Amico's [Ulysses javascript library](https://eyeseast.github.io/ulysses-js/) is a pretty cool way to tell stories with maps, but some coding capability is definitely required.
