### ISSUE TITLE
HTML stripped when adding in slide 

### ISSUE THREAD

**Issue by zkvvoob** [NUKnightLab/StoryMapJS#266]
Hello,

I'd like to deply StoryMapJS on my own server and have HTML5 `<video>` on some slides, displaying locally hosted video files. However, every time I try to paste the pre-prepared HTML code in the 'Create' editor, most of it gets automatically stripped and all I'm left with are `<p>` and `<a>` tags.

What could I do in order to achieve this?

Thank you!

**Comment by JoeGermuska** [comment]
The WYSIWYG editor does do some HTML stripping, as is typical for these kinds of things.

I don't think we're likely to turn that off any time soon, but if you are hosting things on your own server, then you can just edit the JSON file and add in the markup you want.
