### ISSUE TITLE
Support new Mapbox Studio URLs

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#274]
There must not be a lot of demand to use these in StoryMap, but I see that with the updates to Mapbox Studio, the way to specify a custom map has changed.

The mapbox interface offers a URL like `mapbox://styles/nuknightlab/cikplzs9w00ddsykp7vqdz22u`

Right now we only support the old "dotted" style which are used to manually construct a tile URL.

**Comment by JoeGermuska** [comment]
For now, the work around is this: go to the "share, develop and use" page for the specific mapbox "style" you want to use as a baselayer in StoryMap.

In the center (the box labeled "Develop with this style"), click on "leaflet". Copy the "Leaflet URL"

Then, in the StoryMap options, instead of selecting **Map type:** _mapbox_, select **Map type:** _custom_ and paste the URL you copied.

**Comment by kps1ny** [comment]
This work-around resolved the issue for us: we were seeing our data points, but all the tiles showed broken-image icons. Found this solution by searching closed issues for "mapbox."

We are using a stand-alone .json file with the map_type specified in the storymap_options object and changing it from mapbox:cuwebtech.cuwebtech.ciz5wo2s... to https://api.mapbox.com/styles/v1/cuwebtech/ciz5woepk007x2spr3bs3g9kb/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiY3JuMn... did the trick.

**Comment by geodatup** [comment]
that workaround works for me 👍 
```var storymap_options = {map_type:'https://api.mapbox.com/styles/v1/mapbox/navigation-preview-day-v2/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoieW9naXMiLCJhIjoiX3BPdFpWWSJ9.TKVBoQaLtmDdaDOUJkcJ9A'};```

**Comment by JoeGermuska** [comment]
This continues to evolve. While I'd like for us to directly support Mapbox URLs sooner than later, this is an update as to how to get the right URL and configure it.

From your [Mapbox Studio Styles page](https://www.mapbox.com/studio/styles/), select a specific style.

In the section labeled **Use style in GIS apps**, select _CartoDB_ and copy the "integration URL"

![image](https://user-images.githubusercontent.com/46313/30650685-281b5f4c-9de9-11e7-8181-ed8264f5a097.png)

Then, in StoryMap, choose "Options", and from the "Map Type" menu, choose "custom" and paste the URL you copied from MapBox

**Comment by mczirfusz** [comment]
I have a GEOjson tileset uploaded to mapbox, as well as a custom style which I would like to put into work in StoryMapJS (I am using the version on knightlab webpage). Neither of the solutions seem to work for me, Any workaround for that?

**Comment by JoeGermuska** [comment]
We are hoping to resolve this issue this summer. 

It's unlikely that we'll support multiple custom tileset layers in a single StoryMap, at least through the web authoring interface. If it's very important to you, it may be possible to work around it with a custom deployment of StoryMapJS (roughly starting with [these instructions](https://storymap.knightlab.com/advanced/) but also things specific to your case which aren't in those documents.)

What would you be hoping for StoryMapJS to do with your GEOjson tiles?

Regarding your custom style (separate from GEOjson), if you can share the URL you entered in the "custom" field for the "Map Type" option, we may be able to advise further. If you'd rather not post that in GitHub, you can file a [support request](https://knightlab.zendesk.com/hc/en-us/requests/new).

cc @bysimeon

**Comment by mczirfusz** [comment]
thanks, @JoeGermuska 
I would like to use [this](https://api.mapbox.com/styles/v1/czirfusz/cjj5pgk8g0qhf2sqph2gdv2pm.html?fresh=true&title=true&access_token=pk.eyJ1IjoiY3ppcmZ1c3oiLCJhIjoiY2pqNW50bWh5MGRtZTNxbzM3ZWlldzhmNiJ9.VNeiLwWcThcwFGJP4wxxAw#7.19/47.276/19.194) as a background; this is basically the Light core style with an added tileset (the colored dots).

**Comment by JoeGermuska** [comment]
@mczirfusz Ah, I see. I don't know if there's a way for Mapbox to serve those tiles from a single URL, but if there isn't, then proper support would be a much more substantial change to StoryMapJS.  MapBox's service has evolved considerably since StoryMapJS was designed.

Again, using the javascript library directly, I believe one could get access to the LeafletJS map which provides the basic map view, and possibly add a layer to it. This isn't something officially supported, and especially if we were to invest in updating the map core of StoryMapJS, it seems like something which could break. You could pin to a specific StoryMapJS release to protect against that.

Hope this helps a bit. Sorry there isn't a simpler answer.

**Comment by mczirfusz** [comment]
thank you, for the clarification and explanation, @JoeGermuska
