### ISSUE TITLE
Download JSON from authoring tool

### ISSUE THREAD

**Issue by sabas** [NUKnightLab/StoryMapJS#278]
I read on the help that the json file created by the authoring tool is stored on Google Drive
```
If that isn't too daunting, you can find the JSON on your Google Drive in the "KnightLabStoryMap/public" folder.
```

But I can't see this folder (it's hidden from user I read here https://developers.google.com/drive/v3/web/appdata).
How can I download the json?

Thanks!

**Comment by JoeGermuska** [comment]
Those docs are out of date. You can download the json by editing the share URL, but you can't re-upload changes you've made, so manual edits mean moving away from the editor UI. The ability to edit the JSON "in place" is something we had to give up when we gave up on Google Drive, but despite that, StoryMap is much more stable without Google Drive. 

Once you've edited the JSON, you can still use StoryMap to serve it, either by using the instructions at https://storymap.knightlab.com/advanced/ or by putting the JSON on a server somewhere and using a URL like this:
`https://cdn.knightlab.com/libs/storymapjs/latest/embed/index.html?url=[full url to your JSON`

Closing this and folding in the doc update to #277.

**Comment by sabas** [comment]
Ok, so I have to open the share link and find in the source code the 'published.json' right?
Perhaps there could be a 'download json' button into the share panel...

Another question, if I setup the python application on my machine I get an editor instance which saves locally the json, is it correct?
Thanks a lot!

**Comment by JoeGermuska** [comment]
I'm sorry, yeah, I meant to finish the thought and indicate where the JSON is.

Also, unfortunately, no, running the python application locally currently depends upon access to some Amazon S3 store to save the data. Now that you mention it, I wish that it was possible to run it locally this way, and if you're keen to try to change it, I'd love a pull request that made local development use the file system instead of S3 -- but I am not sure when/if we'll have the resources to invest in changing that ourselves.

**Comment by sgoulet** [comment]
Hey @JoeGermuska - trying to follow along here as best I can.  I am trying to see if it makes sense at this point to teach SoryMapJS to some peers in a couple months.  I know that they'll harp on signing in with a Google Account and it saying "Allow Access to Google Drive", but that is no longer the case, correct?  Also is it fair to say that https://storymap.knightlab.com/advanced/ is the most updated docs?  I appreciate your assistance.
