### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated

### ISSUE THREAD

**Issue by Joostvanderlaan** [NUKnightLab/StoryMapJS#287]
getting this error in Chrome 51 on Mac
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

cdn.knightlab.com/libs/timeline3/latest/js/timeline-min.js?2.24:10

**Comment by scott2b** [comment]
@Joostvanderlaan is this still an issue for you? Can you describe how to replicate this? I am not sure when this is happening and how to replicate.

Thanks!

**Comment by MaluNoPeleke** [comment]
I get this warning in the developer console of Chrome 62 as well on https://www.peleke.de/portfolio/

**Comment by gaswirth** [comment]
I'm getting this notice in the dev console as well, using Chromium official build 73
