### ISSUE TITLE
Handle null locations better

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#289]
When there are slides with no location, StoryMap errors ungracefully without clear information about the issue. This is bad.

We should handle this in the authoring tool, with clear warning that the StoryMap is not in a valid state -- possibly also in the "share" panel and maybe even the "select" interface.  We should also do something cleaner -- maybe drop those slides? -- if the StoryMap is viewed anyway.

**Comment by scott2b** [comment]
I'm not sure how to replicate this. How does one create a slide with no location?

**Comment by scott2b** [comment]
The fix of #340 is incomplete. This might be smoothing things out in the editor, but in preview, storymap.js still errors
