### ISSUE TITLE
Unit tests failing on non-UTC timezones

### ISSUE THREAD

**Issue by Hammman** [NUKnightLab/StoryMapJS#291]
QUnit test 3 (asynchronous test: JSON callback) can fail when ran in a non-UTC timezone because http://date.jsontest.com/?callback=? returns UTC time and javascript date objects are in local timezone.

**Comment by scott2b** [comment]
@Hammman I believe your PR #292 was a fix for this. Can you verify this? Thanks!

**Comment by Hammman** [comment]
Yes, this should be all fixed now! Thanks.
