### ISSUE TITLE
UI design for customisable map markers

### ISSUE THREAD

**Issue by qilyn** [NUKnightLab/StoryMapJS#295]
Hi all! Part of the Victoria University group here. We've been working on implementing customisable map markers, and are keen to hear your thoughts about this project. One of the most significant parts of StoryMap is its design, so we thought it would be best to start off this discussion by sharing some of our thoughts about how the UI might look 

**Layout 1 - Separated Modal**
![layout_1_index](https://cloud.githubusercontent.com/assets/18158143/18614490/7445cc12-7de3-11e6-8b7e-c1847ea78475.png)
![layout_1_marker_window](https://cloud.githubusercontent.com/assets/18158143/18614486/7382fa84-7de3-11e6-8d66-afce0b603c3f.png)
**Layout 2 - Combined Slides and Marker Modal**
![layout_2_index](https://cloud.githubusercontent.com/assets/18158143/18614487/73aba57e-7de3-11e6-8d85-4711d85c067f.png)
![layout_2_slidewindow](https://cloud.githubusercontent.com/assets/18158143/18614489/742e7e68-7de3-11e6-8b83-bfe10a982d8e.png)
![layout_2_markerwindow](https://cloud.githubusercontent.com/assets/18158143/18614488/73d5b38c-7de3-11e6-8c64-09ea3f464313.png)

Would these be in keeping with the design of StoryMap? Would you suggest any changes? (binary-koan suggested that we could also have a checkbox for enabling/disabling markers, so I'll update with an example of that of those tomorrow, as well as a snapshot of how the customised markers would look.)

Thanks!

@binary-koan, @Hammman, @JustABitDope

**Comment by binary-koan** [comment]
I also noticed that StoryMap supports having either "icon" markers with no decoration or "image" markers with a border and drop shadow - not sure whether it's worth supporting both styles or just "icon" (and getting people to add their own image effects if they want them).
