### ISSUE TITLE
Link to Slide Example is cut off

### ISSUE THREAD

**Issue by mazhang2718** [NUKnightLab/StoryMapJS#308]
The link to the 'link to specific slide' question is cut off, so it's not possible to easily copy-paste the link into a browser. Reported here: https://knightlab.zendesk.com/agent/tickets/3599

(Also, the link http://s3.amazonaws.com/cdn.knightlab.com/libs/storymapjs/latest/embed/index.html?url=https://ab502fd19d893baee8e6e03e90fbd145f0c62c68.googledrive.com/host/0B1d8oNIpMx53anVuVUFOTXlOVXc/published.json&start_at_slide=5 isn't really working that well, probably because of Gigapixel issues)

**Comment by rosaliechan** [comment]
@rosaliechan

**Comment by rosaliechan** [comment]
Fixed it.  I pushed it to another branch. https://github.com/NUKnightLab/StoryMapJS/blob/LINKCUTOFF/templates/_help.html @mazhang2718 @scott2b

**Comment by mazhang2718** [comment]
We might also want to change the example we use for this, since that link doesn't work anymore...

**Comment by rosaliechan** [comment]
Good point. I just changed it to this link: http://cdn.knightlab.com/libs/storymapjs/latest/embed/?url=//media.knightlab.com/StoryMapJS/demo/sochi.json&start_at_slide=5

**Comment by scott2b** [comment]
I think I would like to see the link itself put into a code block to set it apart from the text. That will still run off the page -- I think `display: block; white-space:normal;` will fix that - although check to be sure

Also, please move styles into the CSS. If necessary you can add an ID to select on, but I suspect applying the style change to `code` in general would be ok (again, verify to be sure)

**Comment by scott2b** [comment]
Also, is "This should load "Descent of the Divine: Panel 2"" a typo? Maybe this is what it was before? I'm not sure what "panel" means here, but the URL loads slide 5

**Comment by rosaliechan** [comment]
Here's the updated one: https://github.com/NUKnightLab/StoryMapJS/blob/LINKCUTOFF/templates/_help.html

Now the link is in a code block that does not run off the page, and also it says This should load "Sochi 2014 Olympic Torch Relay Highlights: Slide 5."

@mazhang2718 @scott2b

**Comment by scott2b** [comment]
yep, and could you add the styles needed so this does not cutoff? Perhaps you already added them to the CSS but didn't commit?

Also, could you create a pull request for this. We will be using PRs for our standard approach to code reviews and discussions

Thanks
