### ISSUE TITLE
Images stretched to fit column width in preview mode

### ISSUE THREAD

**Issue by matty-plumski** [NUKnightLab/StoryMapJS#317]
In preview mode, images are stretched to fit column width, distorting the original aspect ratio. This doesn't seem to carry through to the published version, though, which presents images in original dimensions.
Original:
![panels_normal](https://cloud.githubusercontent.com/assets/3960798/19502849/09e1d406-960c-11e6-9749-55f0deb7f660.PNG)

Stretched in Preview:
![panels_stretched](https://cloud.githubusercontent.com/assets/3960798/19502846/ffb5fb10-960b-11e6-885d-0ebac565a1d1.PNG)

Published: 
![panels_published](https://cloud.githubusercontent.com/assets/3960798/19502852/0f23d810-960c-11e6-889b-e3d91fd91091.PNG)

**Comment by agrahamt** [comment]
Hi Matt, 
Unfortunately it does seem to distort the images when published, here's[ a link to a published example](https://uploads.knightlab.com/storymapjs/29f2dd51f81c24f8305249344c8f0c2b/vectis-scenery/index.html).

If I can't show these engravings at the correct dimensions, I can't use Storymap JS for my project.

Below is a screenshot showing the distorted image in Firefox (on Windows) alongside the original image in Photoshop.
Thanks, Andrew Taylor
![storymapbug_imagedimensions](https://cloud.githubusercontent.com/assets/3066864/20583619/30533d9e-b1b1-11e6-8255-163bf57fe960.gif)

**Comment by triplingual** [comment]
Having the same issue. On Mac 10.12.6, Firefox is fine, Chrome has this issue. Related to #328 perhaps.

**Comment by bysimeon** [comment]
#328 , #148 and this are all caused by the same styling issue in the vco-media's styling. fixing soon.
