### ISSUE TITLE
Google Drive to AWS migration doesn't catch errors

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#327]
Investigating a few Zendesk tickets (eg [3787](https://knightlab.zendesk.com/agent/tickets/3787), [3819](https://knightlab.zendesk.com/agent/tickets/3819), it becomes clear that the code for migrating StoryMaps from Google Drive to AWS/S3 does not do any error checking. It simply writes keys to S3, even though most of those values are actually 404 HTML that looks something like this:

![image](https://cloud.githubusercontent.com/assets/46313/20578813/c4fdf682-b18e-11e6-8bf7-8d6c3e4c71d0.png)

With recent changes to Google Drive, there may be nothing we can do to migrate storymaps automatically for people, but we should at least not give the false impression that the migration was successful.

**Comment by scott2b** [comment]
Migration errors are now caught and the user is directed to contact support. We've gotten a few support requests from this approach so far and it seems to be working well enough. Closing
