### ISSUE TITLE
Google throttling Places API usage

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#329]
Got this report from Matt Taylor:
![screen shot 2016-11-29 at 1 07 41 am](https://cloud.githubusercontent.com/assets/46313/20715293/583a0f1a-b614-11e6-8eff-8308a5e4831a.png)
![screen shot 2016-11-29 at 1 08 49 am](https://cloud.githubusercontent.com/assets/46313/20715294/583d6502-b614-11e6-962c-b05119bf0240.png)

Obviously, throttling is intermittent, so this isn't easily reproduced, but it also tracks with a Zendesk report we got with similar symptoms.

**Comment by scott2b** [comment]
An API key is now being used
