### ISSUE TITLE
Incorrect zoom on Stamen maps terrain

### ISSUE THREAD

**Issue by scott2b** [NUKnightLab/StoryMapJS#338]
The option for selecting stamen maps terrain as the map type causes StoryMap to zoom out much further than what is expected. The zoom level is far enough out so as to be unusable

**Comment by zachwise** [comment]
Stamen maps terrain does not have a closer zoom state. It's also not available in all countries. Maybe we should add this disclaimer on that map option?

**Comment by scott2b** [comment]
ok thanks. Will leave this open then with the action item TODO: document disclaimer about known zoom level issues and location availability for stamen maps. This should go into an appropriate location in the docs. Also, if there is a seamless way to work this into the UI (I'm not sure yet what this would look like) it would be ideal to have this info available to the user when they are selecting this map type

**Comment by JoeGermuska** [comment]
As of earlier this year, Stamen Terrain is global.   we should also see if they added more zoom levels. 

http://maps.stamen.com/

**Comment by scott2b** [comment]
closing as wontfix. Stamen Terrain has now long been removed from the map options

**Comment by marcelaf7** [comment]
The Stamen Terrain map is still listed as an option on the [Technical Details for the JSON syntax](https://storymap.knightlab.com/advanced/#json-syntax). It was pretty confusing until I discovered that it is no longer supported.
