### ISSUE TITLE
Map color

### ISSUE THREAD

**Issue by lucafrassineti** [NUKnightLab/StoryMapJS#346]
I tried the examples in compiled folder, but I see only map in BW and if I try to change the paramtere "language": "it" in json files not work, I made something wrong?
Thanks in advanced

**Comment by rosaliechan** [comment]
Hi @lucafrassineti, do you have a copy of the JSON file?

**Comment by scott2b** [comment]
If this issue persists, please open a support request at knightlab.zendesk.com. Closing
