### ISSUE TITLE
Embedding loses "map overview" and "back to beginning" buttons

### ISSUE THREAD

**Issue by kps1ny** [NUKnightLab/StoryMapJS#347]
Hi. Thanks for making StoryMapJS. We built our first project with it today.

We noticed that when sharing a direct URL to our project, stored on your service, there are buttons for "Map Overview" and "Back To Beginning" at the top left of the map area.

https://uploads.knightlab.com/storymapjs/6b7d971d0ec78095832057eee1022725/nyc/index.html

However, when generating embed code via the sharing option on your web site, the embedded page loses those buttons.

Example here: http://edu.kps1.cuweb.tech/gsl/

Is this a known issue? Something particular to our site?

-Ken

**Comment by JoeGermuska** [comment]
It is something particular to your site: specifically, the "menubar" buttons are actually there; they're just covered up by your banner. Coincidentally, the banner's height is just a little less than the padding above the image on your overview slide, so you don't notice it, but if you look at the two links you sent side by side, you'll see a big difference in the space above the aerial photo of NYC.  

I used the browser inspector to hide the `<header>` element and saw the menubar. One way you could fix this is by putting a `margin-top` on the `iframe` embed.

**Comment by kps1ny** [comment]
Thanks for reviewing our page. I had tried adjusting the margin and padding, to no avail. It turns out that it needed some 200px, about four times what I tried. -Ken

**Comment by JoeGermuska** [comment]
@kps1ny happy to help!
