### ISSUE TITLE
Any new fixes on mobile?

### ISSUE THREAD

**Issue by dariolopezm** [NUKnightLab/StoryMapJS#352]
Hi there. I loved this tool and was selling it to my editor's for an upcoming project until he saw it on mobile. My boss iPhone crashed when he opened the page and it needed a hard reset to come back to life.  I see there have been some previous mobile issues reported but find no fixes. I wish I could help to find a solution. 
Great tool though. 
Dario.

**Comment by thehandsomepanther** [comment]
Hi @dariolopezm, can you provide some more information? What storymap were you trying to view?

**Comment by dariolopezm** [comment]
Joshi, 
This is the map i was planning to make but stopped because itt does not work properly in mobile: 
https://aplataminteractives.atavist.com/trumps-wall

Hope you can help. 
Dario

**Comment by zachwise** [comment]
It looks like it may not be working on mobile because of the images you're using in the storymap. The images are VERY large, each one is around 2.1mb. A normal image size for the web should be between 100-200k. Images that large will very easily overwhelm a phone and possibly cause it to crash.

**Comment by scott2b** [comment]
Agreeing with @zachwise here. This is a good looking StoryMap and works well at mobile viewport sizes on desktop. The troubles on mobile seem to be resource issues we cannot control. Closing
