### ISSUE TITLE
can't create links in the caption section

### ISSUE THREAD

**Issue by thehandsomepanther** [NUKnightLab/StoryMapJS#359]
In the Storymap editor, you can include a link in the description of your slide but not the media caption

**Comment by rosaliechan** [comment]
Are you saying you'd want it to look something like this? @joshshi @scott2b 
<img width="348" alt="screen shot 2017-05-11 at 2 04 17 pm" src="https://cloud.githubusercontent.com/assets/8533482/25967191/e836179e-3652-11e7-97ca-e9236d709d97.png">

**Comment by rosaliechan** [comment]
@zachwise said making this a rich text editor is a lot of chrome for a small subset of users, so I'm just going to add a note saying you can add html, and then eventually work on a modal that pops up when you click on a link that gives html basics (<a href>, <strong>, etc.). Will work on this when I'm in tomorrow.

**Comment by rosaliechan** [comment]
PR here: https://github.com/NUKnightLab/StoryMapJS/pull/365
