### ISSUE TITLE
Allow marker to be shown in Image mode when not hovered over 

### ISSUE THREAD

**Issue by matty-plumski** [NUKnightLab/StoryMapJS#376]
Currently, when the Map is treated as an Image, no location marker appears unless the map is hovered over. It'd be great to have the option to display the current marker alongside the relevant slide without hovering over the map, and toggle this option on or off as desired. (Apologies if this is already an enhancement request!)
![storymapimagenomarker](https://user-images.githubusercontent.com/3960798/29801283-f65ec2b4-8cc2-11e7-932a-36a22e2961ce.jpg)
![storymapimagehoveredmarker](https://user-images.githubusercontent.com/3960798/29801284-f8a1cd78-8cc2-11e7-93dc-e72dd831d03d.jpg)

**Comment by JoeGermuska** [comment]
The intention of the "treat as [image / cartography]" option is to be this switch. Your screenshots show a map, so we'd expect you to use "treat as [cartography]".

**Comment by matty-plumski** [comment]
Fair enough Joe, as you point out there are already two options. Just for context, the request was borne out of users choosing the image option because (I believe) they preferred a cleaner display without the dashed lines connecting markers (which I understand is not necessarily expected behaviour). This request was to see if there's a simple implementation to get the best of both worlds, but I completely appreciate your perspective.

**Comment by JoeGermuska** [comment]
@matty-plumski I am 95% sure it's possible to have no-line-but-always-visible-markers with a manually edited configuration file, but we always try to control the number of movable options in the default user interface, to avoid overwhelming our users.

One of the intentions of the line is to reinforce the narrative aspect, with a specific throughline for the story.

That said, we have heard requests for this before. I wouldn't say "never" but it isn't top priority.

**Comment by matty-plumski** [comment]
Thanks Joe, will look into the manual config approach if this comes up again
