### ISSUE TITLE
More stories into one StoryMapJS

### ISSUE THREAD

**Issue by Gualberto-Vannini** [NUKnightLab/StoryMapJS#379]
There is any way to adding more stories into one map? 

Actually the system permit to add just one "route" with many slides however I want to use many "route" and show them in the same StoryMap. 

for example show : 
Route 1 : Slide 1 - Slide 2 - ........
Route 2: Slide 1 - Slide 2 - ......

And then see both Routes into the map so the people can select the one that they prefer to visit. 

thank you to all

**Comment by JoeGermuska** [comment]
This is not a supported feature, and seems to be at odds with our design goals of simplicity and narrative coherence, so I don't expect it's something we'll add.
