### ISSUE TITLE
add-link button in content editor not working

### ISSUE THREAD

**Issue by scott2b** [NUKnightLab/StoryMapJS#389]
The WYSIWYG add-link button inserts the HTML for an anchor tag but does not provide a mechanism for editing the link destination as expected.

The console error is:

bootstrap-wysihtml5-0.0.2.min.js:1 Uncaught TypeError: Failed to execute 'focus' on 'HTMLElement': parameter 1 ('options') is not an object.
    at HTMLAnchorElement.<anonymous> (bootstrap-wysihtml5-0.0.2.min.js:1)
    at HTMLAnchorElement.dispatch (jquery.min.js:3)
    at HTMLAnchorElement.v.handle (jquery.min.js:3)

Expected behavior, verified to work in Safari and Firefox, is that clicking the link button will introduce a popup for entering a hyperlink.

In Chrome, the link button toggles, but there is no mechanism for entering the link.

**Comment by bysimeon** [comment]
closed by #401
