### ISSUE TITLE
Can't search location on slide: Google Maps API error

### ISSUE THREAD

**Issue by SPrinss** [NUKnightLab/StoryMapJS#390]
###### BUG: 
If I search for a location on slide, the input box states 'undefined' and the marker isn't moved.

###### Console message:
https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
"The current URL loading the Maps JavaScript API has not been added to the list of allowed referrers. Please check the referrer settings of your API key on the Google API Console."

**Comment by scott2b** [comment]
This was the result of an inadvertent configuration change. Fixed now
