### ISSUE TITLE
Text editor: link: URL pop-up should have cursor after prefilled protocol

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#398]
This is minor polish, but it's 🤢 to click on the link button and have the cursor be at the beginning of the field instead of after the pre-filled protocol.

![image](https://user-images.githubusercontent.com/46313/42654749-529dbcea-85df-11e8-9ed8-2573cb7e3eff.png)

However, upon closer review, this may be Firefox only. Still, it's not right.

**Comment by bysimeon** [comment]
closed by #401
