### ISSUE TITLE
Copy function is broken

### ISSUE THREAD

**Issue by scott2b** [NUKnightLab/StoryMapJS#407]
Go to StoryMap List > click the Options gear, select Copy and enter a title and click the Copy button. 

The resulting error is:
Error copying StoryMap: 'Key' object has no attribute 'split'

**Comment by scott2b** [comment]
As a workaround, there is an undocumented import feature that can be used to create a copy. This can be done within the same account or across accounts. To use this feature, you need first to determine the json file you are trying to import. 

Do this based on your published share URL: replace the index.html with published.json. E.g.

https://uploads.knightlab.com/storymapjs/a1a349b51799ee49e96bed10cc235e7f/aryas-journey/index.html

becomes this:

https://uploads.knightlab.com/storymapjs/a1a349b51799ee49e96bed10cc235e7f/aryas-journey/published.json

Then, whatever your json URL is, plug that into the following to initiate the import (be sure you are logged into the account you are trying to copy into):

https://storymap.knightlab.com/select/?import_url=your-json-file.json

**Comment by pelina199** [comment]
When you copy the json url into that import link, it gives the error: "Error loading storymap: NOT FOUND"

**Comment by scott2b** [comment]
It seems likely the URL is not being constructed properly. If the problem persists, please send the link to our Zendesk support at https://knightlab.zendesk.com/. It is not likely to receive follow-up here in Github issues.

**Comment by scott2b** [comment]
fixed

**Comment by scott2b** [comment]
This is apparently still an issue. The error however is:

Error copying StoryMap: 'str' object has no attribute 'name'

**Comment by kig7w** [comment]
I had the same error as pelina199, when I tried to enter the json URL into the link it gave me the error "Error loading storymap: NOT FOUND"

**Comment by scott2b** [comment]
Fixed by fd29bed2af1f44046b0c4fa5b49c47ee80ca1a3b
