### ISSUE TITLE
MS Edge: Navigation arrow not showing due to font loading issues

### ISSUE THREAD

**Issue by scott2b** [NUKnightLab/StoryMapJS#415]
Edge is not seeming to want to download the font used, e.g. for the slide navigation arrow. Relevant code seems to be here: https://github.com/NUKnightLab/TimelineJS3/blob/master/source/less/icons/Icons.less

Edge console shows the ttf font as a resource that is (pending) and never seems to be acquired or throwing an error. Perhaps giving the woff file higher priority than ttf would cause Edge to use this file instead?

**Comment by zachwise** [comment]
The relevant code for StoryMap is here https://github.com/NUKnightLab/StoryMapJS/blob/master/source/less/icons/Icons.less
