### ISSUE TITLE
How to use another map provider other than the default OSM?

### ISSUE THREAD

**Issue by fishfree** [NUKnightLab/StoryMapJS#424]
For example, [this repo](https://github.com/leaflet-extras/leaflet-providers) has many map providers for Leaflet. How to integrate it within StoryMapJS?

**Comment by JoeGermuska** [comment]
Given that most of those providers require registration, with a corresponding need to configure an API key or similar, we're unlikely to complicate the StoryMap user interface with a number of multi-step configuration options. We do this for Mapbox for historic reasons, when they were pretty much the only such option.  

For the `leaflet-providers` plugin to work, ultimately, it is constructing a URL of the same sort which can be entered in the "custom" field of a StoryMap.  At this time, determining how to construct that sort of URL and entering it in the "custom" field is our recommended way of using those map providers.

If people work out how to construct those URLs and want to add them to this Git issue as a reference for the community, that might be a nice thing.

[Disclosure: StoryMap's geocoding service is provided by Mapbox as part of their community program. The ability to configure Mapbox maps predates that arrangement, and is independent of it.]

**Comment by fishfree** [comment]
@JoeGermuska I read the [tutorial](https://storymap.knightlab.com/advanced/), noticed that there was an option of "map_type", which can be a Leaflet TileLayer URL. Could you please give me an detailed example? For I checked all the examples on [the official page](https://storymap.knightlab.com), no usage of this option can be found.

**Comment by JoeGermuska** [comment]
Here is an example of the Stamen Watercolor URL in the appropriate format:
"https://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg"

Storymap's authoring tool allows people to choose that specific one from a menu, but if you used the above URL as the value for "map_type", you'd get the same results as if you used `stamen:watercolor`

If you would like to use one of the providers in the repository you linked, I'd recommend creating a regular Leaflet map and that library, and then use the Network tab of your browser inspector. You'll see the URLs for each tile loaded, and hopefully you can see how to replace the specific server, zoom, and X/Y values with placeholders as in the Leaflet documentation or the example above.

**Comment by fishfree** [comment]
@JoeGermuska Thank you!
