### ISSUE TITLE
Trouble viewing Storymap on mobile

### ISSUE THREAD

**Issue by janemok** [NUKnightLab/StoryMapJS#441]
I have a Storymap embedded onto a website but can't seem to get it started on my mobile phone (IOS) (on the Google Chome app and Safari). The map prompts an OK button but does not respond when pressed.
![IMG_0186](https://user-images.githubusercontent.com/63854173/79566860-d2292780-80e5-11ea-8bf8-bc61111b2c63.PNG)
)

**Comment by JoeGermuska** [comment]
Please provide a link to the storymap that demonstrates this issue.

Visiting storymap.knightlab.com on iOS Safari and iOS Chrome, the embedded example storymap works as expected: tapping "OK" clears the message and allows the storymap to function as normal.

**Comment by janemok** [comment]
https://www.columbiaspectator.com/spectrum/2020/04/17/a-night-out-as-a-columbia-student/ does not seem to work on iOS!

**Comment by JoeGermuska** [comment]
I tried that URL on iOS Safari and Chrome. 

It worked completely on Safari the first time I loaded it. the second time, I was unable to dismiss "swipe to navigate."

On Chrome, the first time I tried it, I was able to dismiss "swipe to navigate" and navigate to the second slide, then no further; the second time, I was unable to dismiss "swipe to navigate." 

I also loaded the storymap directly in iOS Safari Chrome (not embedded in your page) and was able to navigate normally. I tried twice on each browser.

Given this pattern, its impossible to rule out some interaction between the embedded iframe and other content on the host page that is necessarily outside of our control. If you find that you, even intermitttently, experience the issue when directly loading the storymap (by using the URL in the iframe's src attribute), please let us know.  

If in diagnosing interactions with the host page, you can find anything reliably reproducible, we can see if there's something that could be changed about StoryMapJS, but without a test case, there's nothing we can do, and even with one, we would need to consider whether or not the circumstances are something we should support, or if the advice would be for storymap users to avoid creating those circumstances on their host pages.

With inconsistent resultst
