### ISSUE TITLE
vco-map class width doesn't show, and wrong CSS Properties

### ISSUE THREAD

**Issue by narwastunagoro** [NUKnightLab/StoryMapJS#447]
.vco-map {
    height: 100%;
    display: relative;
    overflow: hidden;
    top: 0;
    background-color: #333;
}

missing CSS Properties width and (display:relative;) it should be position:relative;

**Comment by JoeGermuska** [comment]
Seeing as how that mistake has been there for 7 years and hasn't shown any problems, deleting it seems more sensible than changing it.
