### ISSUE TITLE
Storymap deletion assumes maximum number of keys

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/StoryMapJS#456]
I just happened to be looking at the code for `/storymap/delete/` and I see that it arbitrarily assumes that a storymap to be deleted will never have more than 50 associated files stored.

https://github.com/NUKnightLab/StoryMapJS/blob/master/api.py#L493-L511

While this is de facto probably fine, it seems unnecessary to run the risk that a very large storymap would not be correctly deleted (or one for which someone has uploaded extra media in the course of developing the storymap)

Preferably, we'd delete everything without a limit.

**Comment by scott2b** [comment]
An async task now handles asset cleanup for an arbitrary number of keys.
