### ISSUE TITLE
Script breaks on portrait layout

### ISSUE THREAD

**Issue by diniscorreia** [NUKnightLab/StoryMapJS#462]
There seems to be a a bug when the StoryMap loads on smaller devices/portrait layout. 

I'm getting a `ReferenceError: Can't find variable: Animate` on the console — the map doesn't load and, even though the slider works when tapping the arrows, the menu buttons don't work as well. This happens with the examples on the site: https://storymap.knightlab.com/examples/bosch-garden/

**Comment by scott2b** [comment]
This was fixed by 11840a9 and was deployed as 0.8.2 / latest. Please clear your browser's cache and try again. Please let us know if the problem persists.

Note: this is peripherally related to #464 which will be addressed in coming days.
