### ISSUE TITLE
Password for user storymaps: 

### ISSUE THREAD

**Issue by red7-soporte** [NUKnightLab/StoryMapJS#469]
Hi! there..

when I ran create-tables.sh, it asked: Password for user storymap:
![imagen](https://user-images.githubusercontent.com/60528355/132427480-c555ae77-28de-41b0-9758-c88bfc003998.png)
I don't know where I missed it ... in the instructions

Theses are the last lines in the monitor:
pg_1          | PostgreSQL init process complete; ready for start up.
pg_1          | 
pg_1          | 2021-09-07 23:31:36.439 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pg_1          | 2021-09-07 23:31:36.440 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pg_1          | 2021-09-07 23:31:36.458 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pg_1          | 2021-09-07 23:31:36.537 UTC [75] LOG:  database system was shut down at 2021-09-07 23:31:36 UTC
pg_1          | 2021-09-07 23:31:36.556 UTC [1] LOG:  database system is ready to accept connections
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | 
localstack_main | LocalStack version: 0.12.17.5
localstack_main | LocalStack build date: 2021-09-07
localstack_main | LocalStack build git hash: f3449c1c
localstack_main | 
localstack_main | Starting edge router (https port 4566)...
localstack_main | Starting mock S3 service on http port 4566 ...
localstack_main | 2021-09-07T23:31:46:INFO:bootstrap.py: Execution of "load_plugin_from_path" took 636.67ms
localstack_main | 2021-09-07T23:31:46:INFO:bootstrap.py: Execution of "load_plugins" took 637.79ms
localstack_main | [2021-09-07 23:31:46 +0000] [21] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main | 2021-09-07T23:31:46:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main | 2021-09-07T23:31:46:INFO:localstack.multiserver: Starting multi API server process on port 42789
localstack_main | [2021-09-07 23:31:46 +0000] [21] [INFO] Running on http://0.0.0.0:42789 (CTRL + C to quit)
localstack_main | 2021-09-07T23:31:46:INFO:hypercorn.error: Running on http://0.0.0.0:42789 (CTRL + C to quit)
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | Ready.
localstack_main | 2021-09-07T23:31:51:INFO:bootstrap.py: Execution of "start_api_services" took 5705.56ms

any advice? ...
Thanks a lot

**Comment by JoeGermuska** [comment]
These scripts are part of Knight Lab's system for hosting storymap's authoring tool for the general public. 

If you aren't actually trying to set up a version of our authoring tool, you don't even need to worry about that. 

If you are, then while we don't object to someone trying to set up a comparable system using the code in this repository, we don't have the bandwidth/resources to provide proper support, even via GitHub.
