### ISSUE TITLE
not dynamically responsive to window size changes

### ISSUE THREAD

**Issue by scott2b** [NUKnightLab/StoryMapJS#470]
Once StoryMap has been loaded into the window, changing the size of the window does not seem to trigger a re-evaluation of the layout. The result, e.g. when expanding from a smaller to larger window size, is poor layout with doubling of slides or offset of images.

**Comment by michaelgfalk** [comment]
I see the problem in Chrome and not Firefox. The issue appears to be with the 'SCRIPT_PATH' constant. The error occurs [here](https://github.com/NUKnightLab/StoryMapJS/blob/master/src/js/storymap/StoryMap.js#L213)
```
if (Browser.chrome) {
    loadCSS(urljoin(this.options.script_path,"../css/fonts/font.emoji.css"), function() {
        });
}
```
`urljoin` tries to read the length of `this.options.script_path`, but `script_path` is undefined.

**Comment by michaelgfalk** [comment]
See issue #468 

I saw this issue when I tried to create a StoryMap using this example code: https://storymap.knightlab.com/advanced/ 

If you don't include the embedding code that you describe in #468, then there is no value for storymap.options.script_path

Thanks for all you work on this tool.
