### ISSUE TITLE
Increasing the zoom level and adjusting the easterly offset due to zoom level

### ISSUE THREAD

**Issue by brandonlprice** [NUKnightLab/StoryMapJS#484]
Hello,

Is there a basic edit to the code to allow for the maxzoom to be increased? Also, is there a basic edit to the code that would re-center offset maps caused by increased zoom levels? Lastly, are there plans to use a newer version of Leaflet? Great tool by the way, glad to have something like this publicly available.

**Comment by JoeGermuska** [comment]
I'm not really sure what a "basic edit" would be. There aren't configuration options for that, and while the code is open source, I don't think that most folks would find making changes to it to be "basic." 

We're not actively developing StoryMapJS, but there is one possible project on the horizon which might motivate swapping out the current mapping code to something that compiles an external library in, in which case we would use the most current available version of Leaflet. Unfortunately, I can't predict when, or with complete confidence even if that will happen.
